import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "../../public/css/globals.css";
import "../../public/css/contact.css";
import "../../public/css/home.css";
import Header from "@/Component/Header/Header";
// import 'bootstrap/dist/css/bootstrap.min.css'; // Import Bootstrap CSS


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <Header />
        {children}
      </body>
    </html>
  );
}
